### ISSUE TITLE
InvalidOperationException : Process must exit before requested information can be determined upon cancellation

### ISSUE THREAD

**Issue by borland** [OctopusDeploy/Shellfish#133]
Encountered in a [failed TeamCity build](https://build.octopushq.com/buildConfiguration/OctopusDeploy_Libraries_Shellfish_TestLinux/15157745?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true&expandPull+Request+Details=true)

```
Failed Tests.ShellCommandFixtureStdInput.ShouldBeCancellable(behaviour: Async) [8 ms]
Error Message:
 System.InvalidOperationException : Process must exit before requested information can be determined.
Stack Trace:
   at System.Diagnostics.Process.EnsureState(State state)
 at System.Diagnostics.Process.get_ExitCode()
 at Octopus.Shellfish.ShellCommandExecutorHelpers.SafelyGetExitCode(Process process) in /opt/buildagent/work/c4d67eb417aa367f/source/Shellfish/ShellCommandExecutorHelpers.cs:line 21
 at Octopus.Shellfish.ShellCommand.ExecuteAsync(CancellationToken cancellationToken) in /opt/buildagent/work/c4d67eb417aa367f/source/Shellfish/ShellCommand.cs:line 243
 at Tests.ShellCommandFixtureStdInput.ShouldBeCancellable(SyncBehaviour behaviour) in /opt/buildagent/work/c4d67eb417aa367f/source/Tests/ShellCommandFixture.StdInput.cs:line 228
```

# Analysis

The relevant code is (edited for brevity) doing this:

```csharp
try {
    await exitedTask.ConfigureAwait(true);
}
catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested) {
    TryKillProcessAndChildrenRecursively(process);
}
// Exception thrown from SafelyGetExitCode
return new ShellCommandResult(SafelyGetExitCode(process));
```

What is most likely happening.
- On linux, `TryKillProcessAndChildrenRecursively` is implemented by [sending a SIGTERM to the process.](https://github.com/OctopusDeploy/Shellfish/blob/8633da4e2a93cc6399dae67c0ae8666263e9453e/source/Shellfish/Nix/NixAdapter.cs#L19)
- SIGTERM is a message asking the process to exit itself. It may not exit immediately, or even if it is trying to, it may not be fast enough before we try and get the exit code

**Comment by adam-mccoy** [comment]
If I'm understanding the proposed fix correctly, on cancellation the reported exit code will vary between success (0) if the process managed to exit on time, or -1 if it didn't. If anything, I think the result should consistently be -1 in this situation.
